version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: work_trial_user
      POSTGRES_PASSWORD: lk123je6e9y342a2dccadf5ai5eu5g55mh
      POSTGRES_DB: work_trial
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
